#:schema node_modules/wrangler/config-schema.json
name = "itty-id"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
routes = [
  "itty.id/*",
  "itty.id"
]
